using UnityEngine;

public class Magatama : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }




     void OnTriggerEnter(Collider other)
    {
        //Debug.Log("Õ“Ë‘Šè: " + other.name); // © ‚±‚ê’Ç‰ÁI

        Player player = other.GetComponentInParent<Player>();
        if (player != null)
        {

            //Debug.Log($"PlayerID: {player.playerID} ‚ªŒù‹Ê‚ğæ“¾");
            player.AddMagatama();
            Destroy(gameObject); // æ“¾ŒãÁ‚·
        }
    }


}
